<?php

namespace SecretBundle\Repository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * UserPresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPresenceRepository extends \Doctrine\ORM\EntityRepository
{

    private function trainingTime()
    {
        $now = new \DateTime('now');
        $lastPresence = new \DateTime("now");
        $lastPresence->sub(date_interval_create_from_date_string('80 minutes'));

        return ['now' => $now, 'lastPresence' =>$lastPresence];
    }

    public function findLastPresence(int $userInfoId)
    {
        $time = $this->trainingTime();

        $qb = $this->createQueryBuilder('up');
        $qb
            ->where('up.presence = :userInfoId')
            ->andWhere('up.presenceDate BETWEEN :lastPresence AND :now' )
            ->setParameter('userInfoId', $userInfoId)
            ->setParameter('lastPresence', $time['lastPresence'])
            ->setParameter('now', $time['now']);

        $query = $qb->getQuery();
        return $result = $query->getOneOrNullResult();
    }

    public function findPresenceList()
    {
        $time = $this->trainingTime();

        $qb = $this->createQueryBuilder('up');
        $qb
            ->where('up.presenceDate BETWEEN :lastPresence AND :now' )
            ->setParameter('lastPresence', $time['lastPresence'])
            ->setParameter('now', $time['now']);

        return $query = $qb->getQuery();
    }

}
